### ISSUE TITLE
@-ms-viewport becomes @viewport

### ISSUE THREAD

**Issue by Grawl** [gucong3000/postcss-clean-prefixes#119]
It's unexpected behaviour

```css
@-ms-viewport {
  width: device-width;
}
```

```css
@viewport {
  width: device-width;
}
```

https://timkadlec.com/2012/10/ie10-snap-mode-and-responsive-design/
