### ISSUE TITLE
-webkit-text-decoration-skip is removed

### ISSUE THREAD

**Issue by Grawl** [gucong3000/postcss-clean-prefixes#120]
It's unexpected behaviour

```css
a {
  text-decoration: none;
  -webkit-text-decoration-skip: objects;
}
```

```css
a {
  text-decoration: none;
}
```
